const data = {
  products: [
    {
      _id: "1",
      name: "Prod1",
      image: "https://via.placeholder.com/680x830.png?text=img1+680x830",
      price: 120,
      countInStock: 10,
      brand: "brand1",
      rating: 1.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      _id: 2,
      name: "Prod2",
      image: "https://via.placeholder.com/680x830.png?text=img2+680x830",
      price: 122,
      countInStock: 10,
      brand: "brand2",
      rating: 0.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      _id: 3,
      name: "Prod3",
      image: "https://via.placeholder.com/680x830.png?text=img3+680x830",
      price: 123,
      countInStock: 10,
      brand: "brand3",
      rating: 3,
      numReviews: 10,
      description: "Good product",
    },
    {
      _id: 4,
      name: "Prod4",
      image: "https://via.placeholder.com/680x830.png?text=img4+680x830",
      price: 124,
      countInStock: 4,
      brand: "brand4",
      rating: 5,
      numReviews: 10,
      description: "Good product",
    },
    {
      _id: 5,
      name: "Prod5",
      image: "https://via.placeholder.com/680x830.png?text=img5+680x830",
      price: 125,
      countInStock: 0,
      brand: "brand5",
      rating: 0,
      numReviews: 10,
      description: "Good product",
    },
    {
      _id: 6,
      name: "Prod6",
      image: "https://via.placeholder.com/680x830.png?text=img6+680x830",
      price: 126,
      countInStock: 8,
      brand: "brand6",
      rating: 4.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      _id: 7,
      name: "Prod7",
      image: "https://via.placeholder.com/680x830.png?text=img7+680x830",
      price: 127,
      countInStock: 10,
      brand: "brand7",
      rating: 4.5,
      numReviews: 10,
      description: "Good product",
    },
  ],
};

export default data;