import bcrypt from "bcrypt";
const data = {
  users: [
    {
      name: "Anurag",
      email: "sinha.anurag101@gmail.com",
      password: bcrypt.hashSync("mypwd", 8),
      isAdmin: true,
    },
    {
      name: "Ayushi",
      email: "ayushipandegeu@gmail.com",
      password: bcrypt.hashSync("mypwd", 8),
      isAdmin: false,
    },
  ],
  products1: [
    {
      name: "Prod1",
      image: "assets/products/1.webp",
      price: 120,
      countInStock: 10,
      brand: "brand1",
      category: 1,
      subCategory: 102,
      rating: 1.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod2",
      image: "assets/products/2.webp",
      price: 122,
      countInStock: 10,
      brand: "brand2",
      category: 1,
      subCategory: 102,
      rating: 0.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod3",
      image: "assets/products/3.webp",
      price: 123,
      countInStock: 10,
      brand: "brand3",
      category: 2,
      subCategory: 203,
      rating: 3,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod4",
      image: "assets/products/4.webp",
      price: 124,
      countInStock: 4,
      brand: "brand4",
      category: 3,
      subCategory: 301,
      rating: 5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod5",
      image: "assets/products/5.webp",
      price: 125,
      countInStock: 0,
      brand: "brand5",
      category: 4,
      subCategory: 402,
      rating: 0,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod6",
      image: "assets/products/6.webp",
      price: 126,
      countInStock: 8,
      brand: "brand6",
      category: 4,
      subCategory: 401,
      rating: 4.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod7",
      image: "assets/products/7.webp",
      price: 127,
      countInStock: 10,
      brand: "brand7",
      category: 2,
      subCategory: 203,
      rating: 4.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod8",
      image: "assets/products/8.webp",
      price: 128,
      countInStock: 80,
      brand: "brand8",
      category: 12,
      subCategory: 210,
      rating: 4.5,
      numReviews: 10,
      description: "Good product",
    },
  ],
  products: [
    {
      name: "Prod41",
      image: "assets/products/1.webp",
      price: 120,
      countInStock: 10,
      brand: "brand1",
      category: 2,
      subCategory: 203,
      rating: 1.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod42",
      image: "assets/products/2.webp",
      price: 122,
      countInStock: 10,
      brand: "brand2",
      category: 2,
      subCategory: 203,
      rating: 0.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod43",
      image: "assets/products/3.webp",
      price: 123,
      countInStock: 10,
      brand: "brand3",
      category: 2,
      subCategory: 203,
      rating: 3,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod44",
      image: "assets/products/4.webp",
      price: 124,
      countInStock: 4,
      brand: "brand4",
      category: 2,
      subCategory: 203,
      rating: 5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod45",
      image: "assets/products/5.webp",
      price: 125,
      countInStock: 0,
      brand: "brand5",
      category: 2,
      subCategory: 203,
      rating: 0,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod46",
      image: "assets/products/6.webp",
      price: 126,
      countInStock: 8,
      brand: "brand6",
      category: 2,
      subCategory: 203,
      rating: 4.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod47",
      image: "assets/products/7.webp",
      price: 127,
      countInStock: 10,
      brand: "brand7",
      category: 2,
      subCategory: 203,
      rating: 4.5,
      numReviews: 10,
      description: "Good product",
    },
    {
      name: "Prod48",
      image: "assets/products/8.webp",
      price: 128,
      countInStock: 80,
      brand: "brand8",
      category: 2,
      subCategory: 203,
      rating: 4.5,
      numReviews: 10,
      description: "Good product",
    },
  ],
  CategoryData: [
    {
      _id: 1,
      categoryName: "Grocery",
      subCategories: [
        { _id: 101, name: "Pulses" },
        { _id: 102, name: "ATTA" },
        { _id: 103, name: "Other Flours" },
        { _id: 104, name: "Rice" },
        { _id: 105, name: "Other Grains" },
        { _id: 106, name: "Dry Fruits & Nuts" },
        { _id: 107, name: "Edible Oils" },
        { _id: 108, name: "Ghee & Vanaspati" },
        { _id: 109, name: "Spices" },
        { _id: 110, name: "Salt" },
        { _id: 111, name: "Sugar & Jaggery" },
      ],
    },
    {
      _id: 2,
      categoryName: "Personal Care",
      subCategories: [
        { _id: 201, name: "Bath & Body" },
        { _id: 202, name: "Hair Care" },
        { _id: 203, name: "Skin Care" },
        { _id: 204, name: "Oral Care" },
        { _id: 205, name: "Face Care" },
        { _id: 206, name: "Men's Grooming" },
        { _id: 207, name: "Women's Grooming" },
        { _id: 208, name: "Fragrances" },
        { _id: 209, name: "Cosmetics" },
        { _id: 210, name: "Health & Wellness" },
      ],
    },
    {
      _id: 3,
      categoryName: "Household",
      subCategories: [
        { _id: 301, name: "Repellents" },
        { _id: 302, name: "Laundry Detergents" },
        { _id: 303, name: "Cleaners" },
        { _id: 304, name: "Dishwashers" },
        { _id: 305, name: "Liquid Detergents" },
        { _id: 306, name: "Disinfectants" },
        { _id: 307, name: "Tissue & Disposables" },
        { _id: 308, name: "Pooja Needs" },
        { _id: 309, name: "Home & car Fresheners" },
        { _id: 310, name: "Shoe Care" },
        { _id: 311, name: "Cleaning Tools & Brushes" },
      ],
    },
    {
      _id: 4,
      categoryName: "Snacks",
      subCategories: [
        { _id: 401, name: "Chocolates" },
        { _id: 402, name: "Biscuits & Cookies" },
        { _id: 403, name: "Namkeen & Snacks" },
        { _id: 404, name: "Chips & Crisps" },
        { _id: 405, name: "Sweets" },
        { _id: 406, name: "Confectionery" },
      ],
    },
    {
      _id: 5,
      categoryName: "Beverages",
      subCategories: [
        { _id: 501, name: "Cold Drinks" },
        { _id: 502, name: "Juices & Drinks" },
        { _id: 503, name: "Tea" },
        { _id: 504, name: "Coffee" },
        { _id: 505, name: "Health & Energy Drinks" },
        { _id: 506, name: "Water & Soda" },
        { _id: 507, name: "Milk Drinks" },
      ],
    },
  ],
};

export default data;
