export const CATEGORY_DATA_REQUEST = "CATEGORY_DATA_REQUEST";
export const CATEGORY_DATA_SUCCESS = "CATEGORY_DATA_SUCCESS";
export const CATEGORY_DATA_FAIL = "CATEGORY_DATA_FAIL";

export const CATEGORY_PRODUCT_DATA_REQUEST = "CATEGORY_PRODUCT_DATA_REQUEST";
export const CATEGORY_PRODUCT_DATA_SUCCESS = "CATEGORY_PRODUCT_DATA_SUCCESS";
export const CATEGORY_PRODUCT_DATA_FAIL = "CATEGORY_PRODUCT_DATA_FAIL";
