export const SET_ADMIN_PAGE = "SET_ADMIN_PAGE";
export const SET_NON_ADMIN_PAGE = "SET_NON_ADMIN_PAGE";

export const STORE_DATA_REQUEST = "STORE_DATA_REQUEST";
export const STORE_DATA_SUCCESS = "STORE_DATA_SUCCESS";
export const STORE_DATA_FAIL = "STORE_DATA_FAIL";
